"""Solver c extension module."""

def load_instance(file_path: str) -> tuple: ...
def objective_value(tour, dimension): ...
def twist_move(tour): ...
def random_removal(instance, tour, num_vertices_to_remove): ...
def worst_removal(instance, tour, num_vertices_to_remove): ...
def cluster_removal(instance, tour, num_vertices_to_remove): ...
def cheapest_insertion(
    instance, tour, num_node, nodes_to_insert, num_nodes_to_insert
): ...
def nearest_insertion(
    instance, tour, num_node, nodes_to_insert, num_nodes_to_insert
): ...

class TSPInstance:
    """TSP instance class."""

    @property
    def dimension(self): ...
    @property
    def instance_name(self): ...
